name: Nightly Tests

on:
  schedule:
    - cron: "0 5 * * 3,5"  # cron is UTC, this translates to 10 PM PST Tues and Thur.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

jobs:
  ios-nightly:
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceSDKCommon, SalesforceAnalytics, SalesforceSDKCore, SmartStore, MobileSync]
        macos: [macos-15]
        include:
          # iOS 26 on Xcode 26 (will fail until both versions become available)
          - ios: ^26
            xcode: ^26
          # iOS 18 on Xcode 26 (will fail until Xcode 26 becomes available)
          - ios: ^18
            xcode: ^26
          # iOS 18 on Xcode 16
          - ios: ^18
            xcode: ^16
          # iOS 17 (latest) on Xcode 15 (latest)
          - ios: ^17
            xcode: ^15
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      macos: ${{ matrix.macos }}
    secrets: inherit