on:
  workflow_call:
    inputs:
      lib:
        required: true
        type: string
      ios:
        default: "^18"
        required: false
        type: string
      xcode:
        default: "^16"
        required: false
        type: string
      macos:
        default: macos-15
        required: false
        type: string
      is_pr:
        type: boolean
        default: false

jobs:
  test-ios:
    runs-on: ${{ inputs.macos }}
    steps:
      - uses: actions/checkout@v4
        if: ${{ inputs.is_pr }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v4
        if: ${{ ! inputs.is_pr }}
        with:
          ref: ${{ github.head_ref }}
      - name: Install Dependencies
        env:
          TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
        run: |
          ./install.sh
          echo $TEST_CREDENTIALS > ./shared/test/test_credentials.json
      - name: Set Xcode Version
        run: |
          echo "Setting Xcode version to ${{ inputs.xcode }}"
          # For specific versions like 16.4, ensure Xcode path exists
          if [[ "${{ inputs.xcode }}" =~ ^[0-9]+\.[0-9]+$ ]]; then
            XCODE_PATH="/Applications/Xcode_${{ inputs.xcode }}.app"
            if [ -d "$XCODE_PATH" ]; then
              sudo xcode-select -s "$XCODE_PATH"
              echo "Set Xcode to specific version: ${{ inputs.xcode }}"
            else
              echo "Warning: Xcode ${{ inputs.xcode }} not found at $XCODE_PATH, using mxcl/xcodebuild action to handle version"
            fi
          fi
          xcodebuild -version
      - uses: mxcl/xcodebuild@v3
        with:
          xcode: ${{ inputs.xcode }}
          platform: iOS
          platform-version: ${{ inputs.ios }}
          workspace: SalesforceMobileSDK.xcworkspace
          scheme: ${{ inputs.lib }}
          code-coverage: true
          verbosity: xcbeautify
      - uses: slidoapp/xcresulttool@v3.1.0
        with:
          path: test.xcresult
          title: "${{ inputs.lib }} iOS ${{ inputs.ios }}"
          show-code-coverage: false
          upload-bundles: false
          show-passed-tests: false
        if: success() || failure()
      - uses: codecov/codecov-action@v4
        with:
          flags: ${{ inputs.lib }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: success() || failure()
